#PBS -l walltime=10:10:00
#PBS -l nodes=1:ppn=6:gpus=2
#PBS -q gpufermi
#PBS -N diaria
#PBS -j oe

export CUDA_VISIBLE_DEVICES=`gpu-free`

echo "Your job is running in:"
cat $PBS_NODEFILE

module load python/2.7.5/pycasp
module load hdf5
module load python
module load cuda

cd $PBS_O_WORKDIR

for i in `ls -d -1 $PWD/test_cfg/*` ; do
        cp -r cluster.py $i $PFSDIR
	cd $PFSDIR
	python cluster.py -c $i
done


cp * $PBS_O_WORKDIR

